### ISSUE TITLE
"obp_well" notebook - error when trying to view the fitted density trend

### ISSUE THREAD

**Issue by salsa360** [whimian/pyGeoPressure#10]
Hi Yu Hao,

I've tried running your "obp_well" notebook and keep getting the following error when trying to view 
 the fitted density trend:

"RuntimeWarning: invalid value encountered in power
  return 1.70 + a * z**b"

![obp_well notebook - error message](https://user-images.githubusercontent.com/48823169/55434169-83d3e400-55c9-11e9-9199-39fa3b6e92cf.png)

**Comment by whimian** [comment]
Warnings are not errors. If `np.nan` is inputted to the calculation, warnings will raised. But nothing is going wrong, it's just informing us, the output will be `np.nan` as expected.
