### ISSUE TITLE
Community Guidelines / Contribution

### ISSUE THREAD

**Issue by JesperDramsch** [whimian/pyGeoPressure#8]
Hej @whimian,

could you add a couple sentences, how you would prefer people to contribute to this package? 
It would be great, if you could detail the following points in a dedicated paragraph:

- [ ] Contribute to the software
- [ ] Report issues or problems with the software
- [ ] Seek support

**Comment by whimian** [comment]
Does f06b816b15df65cfa43273bc5fe0e12bb2498d11 make it clearer?

**Comment by JesperDramsch** [comment]
Yes, that is really great.
